package main

const (
	ERROR_CODE_NONE = 0

	ERROR_CODE_PACKET_ENCODING_FAIL       = 50
	ERROR_CODE_PACKET_DECODING_FAIL       = 51

	ERROR_CODE_LOGIN_USER_INVALID_ID    = 112
	ERROR_CODE_LOGIN_USER_INVALID_PW    = 114

	ERROR_CODE_ENTER_ROOM_PACKET_DECODING_FAIL = 141
	ERROR_CODE_ENTER_ROOM_MQ_PACKET_DECODING_FAIL = 143

	ERROR_CODE_LEAVE_ROOM_MQ_PACKET_DECODING_FAIL = 151
	/*
	ERROR_CODE_ENTER_ROOM_ALREADY               = 131
	ERROR_CODE_ENTER_ROOM_PREV_WORKING          = 132
	ERROR_CODE_ENTER_ROOM_INVALID_USER_ID       = 133
	ERROR_CODE_ENTER_ROOM_USER_FULL             = 134
	ERROR_CODE_ENTER_ROOM_DUPLCATION_USER       = 135
	ERROR_CODE_ENTER_ROOM_INVALID_SESSION_STATE = 136
	ERROR_CODE_ENTER_ROOM_AUTO_ROOM_NUMBER      = 137

	ERROR_CODE_LEAVE_ROOM_INTERNAL_INVALID_USER = 141
	ERROR_CODE_LEAVE_ROOM_STATE_PLAYING_GAME    = 142

	ERROR_CODE_ROOM_CHAT_CHAT_MSG_LEN = 151

	ERROR_CODE_ROOM_RELAY_FAIL_DECPDING = 161

	ERROR_CODE_ROOM_GAME_START_INVALID_ROOM_STATE = 171
	ERROR_CODE_ROOM_GAME_START_NOT_ENOUGH_MEMBERS = 172

	ERROR_CODE_ROOM_PLAY_GAME_FAIL_PACKET         = 181
	ERROR_CODE_ROOM_PLAY_GAME_INVALID_ROOM_STATE  = 182
	ERROR_CODE_ROOM_PLAY_GAME_INVALID_CARD_SELECT = 183
	ERROR_CODE_ROOM_PLAY_GAME_TAKE_INVALID_CARD   = 184
	ERROR_CODE_ROOM_PLAY_GAME_USER_NOT_TURN       = 185

	ERROR_CODE_ROOM_PLAY_GAME_SHAKING_FAIL    = 186
	ERROR_CODE_ROOM_PLAY_GAME_BOMB_COUNT_FAIL = 187*/
)
