package main

// 1 ~ 1000
const (
	PACKET_ID_PING_REQ = 201
	PACKET_ID_PING_RES = 202

	PACKET_ID_ERROR_NTF = 203

	PACKET_ID_SESSION_CLOSE_SYS = 211

	// Inner Packet
	INNER_PACKET_ID_LOGIN_REQ = 300
	INNER_PACKET_ID_LOGIN_RES = 301
	INNER_PACKET_ID_LOGIN_NTF = 302

	INNER_PACKET_ERROR_NTF = 400
	//////////////////////////

	PACKET_ID_C2S_START = 700 // 논리적인 의미로 클라이언트-서버 패킷의 시작 번호
	PACKET_ID_LOGIN_REQ = 701
	PACKET_ID_LOGIN_RES = 702

	PACKET_ID_ROOM_ENTER_REQ = 721
	PACKET_ID_ROOM_ENTER_RES = 722

	PACKET_ID_ROOM_LEAVE_REQ = 726
	PACKET_ID_ROOM_LEAVE_RES = 727
	PACKET_ID_ROOM_LEAVE_NTF = 728

	PACKET_ID_ROOM_CHAT_REQ    = 731
	PACKET_ID_ROOM_CHAT_RES    = 732
	PACKET_ID_ROOM_CHAT_NOTIFY = 733

	PACKET_ID_C2S_END = 1000
)
