package protocol

const (
	ERROR_CODE_NONE = 0

	ERROR_CODE_PACKET_DECODING_FAIL           = 51

	ERROR_CODE_LOGIN_USER_DUPLICATION  = 111
	ERROR_CODE_LOGIN_USER_INVALID_ID   = 112

	ERROR_CODE_START_WATCHING_INVALID_AUTH         = 121
	ERROR_CODE_START_WATCHING_ALREADY         = 122
	ERROR_CODE_START_WATCHING_FAIL_CONNECT         = 123

)
