<?php

class ErrorCode
{
    const NONE = 0;

    // 11에서 200까지
    const USER_ADD_FAIL = 11;

    const ENTER_ROOM_INVALID_ROOM_NUMBER = 21;
    const ENTER_ROOM_DUP_USER = 22;
    const ENTER_ROOM_FULL_USER = 23;
    const ENTER_ROOM_USER_ALREADY = 24;

    const LEAVE_ROOM_INVALID_ROOM_NUMBER = 31;

    const CHAT_ROOM_INVALID_ROOM_NUMBER = 41;

    const GAME_START_INVALID_USER = 101;
    const GAME_START_INVALID_ROOM_STATE = 102;
    const GAME_START_INVALID_ROOM_USER_COUNT = 103;

    const GAME_PLAYER_TURN_INVALID_USER = 111;
    const GAME_PLAYER_TURN_INVALID_ROOM_STATE = 112;
    const GAME_PLAYER_TURN_INVALID_TURN = 114;
    const GAME_PLAYER_TURN_INVALID_THROW_PAE_NUMBER = 118;
    const GAME_PLAYER_TURN_INVALID_BADAG_PAE_NUMBER = 119;
    const GAME_PLAYER_TURN_NOT_SAME_THROW_BADAG_PAE_NUMBER = 120;
}